export const USERS = [
  {
    id: 1,
    initials: 'JC',
    name: 'Josh Carper',
    location: 'Mississippi, US',
    role: 'UI Designer',
    joined: 'Jan 2025',
    offer: ['UI Design', 'Figma'],
    want: ['Painting', 'Photography'],
    availability: 'Available Now',
    color: '#298C6E',
    swaps: 8,
    rating: 4.8,
    bio: 'UI designer with 3 years of experience. Love creating clean interfaces and want to explore creative arts on the side.',
    reviews: [
      { initials: 'MJ', name: 'Michael J.', rating: 5, text: 'Great to work with. Very knowledgeable about UI principles.', date: 'Mar 10' },
      { initials: 'BS', name: 'Brad S.',    rating: 5, text: 'Josh is a fantastic teacher. Highly recommend!',            date: 'Feb 22' },
    ],
  },
  {
    id: 2,
    initials: 'MJ',
    name: 'Michael J.',
    location: 'California, US',
    role: 'Software Engineer',
    joined: 'Feb 2025',
    offer: ['Java', 'Python'],
    want: ['Data Analyst', 'Excel'],
    availability: 'Available Now',
    color: '#298C6E',
    swaps: 5,
    rating: 4.6,
    bio: 'Backend developer looking to expand into data analysis. Happy to trade programming knowledge.',
    reviews: [
      { initials: 'HT', name: 'Harry T.', rating: 5, text: 'Very patient and thorough. Learned a lot!', date: 'Mar 15' },
    ],
  },
  {
    id: 3,
    initials: 'BS',
    name: 'Brad Sanchez',
    location: 'Texas, US',
    role: 'Calligrapher',
    joined: 'Mar 2025',
    offer: ['Calligraphy', 'Drawing'],
    want: ['MS Excel', 'Data Analysis'],
    availability: 'Weekdays',
    color: '#298C6E',
    swaps: 3,
    rating: 4.9,
    bio: 'Professional calligrapher wanting to learn more about spreadsheets and data for my small business.',
    reviews: [
      { initials: 'LG', name: 'Lian G.', rating: 5, text: 'Brad is incredibly talented. Amazing experience.', date: 'Mar 20' },
    ],
  },
  {
    id: 4,
    initials: 'HT',
    name: 'Harry Tompson',
    location: 'Arizona, US',
    role: 'Statistician',
    joined: 'Jan 2025',
    offer: ['Statistics', 'Finance'],
    want: ['Finance', 'Accounting'],
    availability: 'Weekends',
    color: '#298C6E',
    swaps: 12,
    rating: 4.7,
    bio: 'Stats professional who loves teaching numbers and wants to grow in finance.',
    reviews: [
      { initials: 'KA', name: 'Kyla A.', rating: 5, text: 'Harry explains complex topics really clearly.', date: 'Feb 28' },
    ],
  },
  {
    id: 5,
    initials: 'MS',
    name: 'Maria Sanchez',
    location: 'New York City',
    role: 'UI/UX Designer',
    joined: 'Aug 2025',
    offer: ['UI/UX Design', 'Figma Prototyping', 'Illustration'],
    want: ['Photography basics', 'Calligraphy'],
    availability: 'Available Now',
    color: '#298C6E',
    swaps: 12,
    rating: 4.5,
    bio: 'BSIT student passionate about design and user experience. I\'ve been using Figma for 4 years and love helping others learn it. Looking to build my tech skills — especially Photography and Calligraphy — through skills exchange.',
    reviews: [
      { initials: 'JL', name: 'James L.',  rating: 5, text: 'Maria is an excellent teacher. She explained Figma components clearly and was very patient. Highly recommended!', date: 'Mar 10' },
      { initials: 'AM', name: 'Amelia M.', rating: 5, text: 'Great experience swapping skills. Very reliable and organized. Would swap again.',                                date: 'Feb 28' },
    ],
  },
]

export const SWAP_REQUESTS = [
  { id: 1, requester: 'Aaron M.',   exchange: 'UI Design ↔ Calligraphy',      status: 'Pending', date: 'Mar 24' },
  { id: 2, requester: 'Sarah F.',   exchange: 'Programming ↔ Painting',       status: 'Active',  date: 'Mar 12' },
  { id: 3, requester: 'Emily R.',   exchange: 'Drawing ↔ Painting',           status: 'Done',    date: 'Mar 10' },
  { id: 4, requester: 'Jasper L.',  exchange: 'English ↔ Spanish',            status: 'Done',    date: 'Mar 16' },
  { id: 5, requester: 'Francis P.', exchange: 'Video editing ↔ Excel',        status: 'Active',  date: 'Mar 9'  },
]